name: XU CHENG
author: Xu Cheng
url: https://xuc.me
twitter_username: _xucheng_
github_username: xu-cheng
google_analytics_id: UA-4293090-10

markdown: kramdown
highlighter: pygments
feed:
  path: blog.xml
exclude:
  - .gitignore
  - .travis.yml
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor
lsi: false
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap

permalink: /blog/:title/

navigation:
  - title: home
    link: /
  - title: blog
    link: /blog/
  - title: contact
    link: /contact/
