title: XU CHENG
author: Xu Cheng
url: https://xuc.me
uuid: fc6e15bc-f87d-4081-83d3-ac681a90498e # Using for atom id (blog.xml)
twitter_username: _xucheng_
github_username: xu-cheng
google_analytics_id: UA-4293090-10

markdown: kramdown
highlighter: pygments
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
lsi: false
gems:
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap

permalink: /blog/:title/

navigation:
  - title: home
    link: /
  - title: research
    link: /research/
  - title: blog
    link: /blog/
  - title: contact
    link: /contact/
